### ISSUE TITLE
Username & password for first login

### ISSUE THREAD

**Issue by christianyohanes04** [Telecominfraproject/wlan-cloud-ucentral-deploy#114]
Hello, i cannot loggin to CloudSDK Controller? I've followed the tutorial on github but it doesn't work

**Comment by hackeren** [comment]
> Hello, i cannot loggin to CloudSDK Controller? I've followed the tutorial on github but it doesn't work

me too

**Comment by carsten989** [comment]
Don't think anybody is really monitoring GH issues here.
If this is still an issue for you, please create a JIRA issue at https://telecominfraproject.atlassian.net/jira/
Also feel free to post on Slack.
