### ISSUE TITLE
A problem occurred when I tried to import the CA into the browser

### ISSUE THREAD

**Issue by liam-sdc** [Telecominfraproject/wlan-cloud-ucentral-deploy#116]
I try to build a cloud on my personal computer (ubuntu2004) to test the connectivity of the AP, as follows:
[Non-LB deployment with self-signed certificates](https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/tree/main/docker-compose#non-lb-deployment-with-self-signed-certificates)

The following problem occurred when I tried to import CA by visiting the specified URL(https://[openwifi.wlan.local](https://openwifi.wlan.local:16001/):16001/):
`{"ErrorCode":400,"ErrorDescription":"1004: Unsupported HTTP Method","ErrorDetails":"GET"}`

Guys, any suggestions?

**Comment by carsten989** [comment]
Don't think anybody is really monitoring GH issues here.
If this is still an issue for you, please create a JIRA issue at https://telecominfraproject.atlassian.net/jira/
Also feel free to post on Slack.
