### ISSUE TITLE
default Login credential error

### ISSUE THREAD

**Issue by Ortiz25** [Telecominfraproject/wlan-cloud-ucentral-deploy#267]
The default web ui Login Credentials (Default user is: tip@ucentral.com and password is: openwifi) are not working, I get an error every time I try to login. Installed the SDK using docker, Kindly assist

**Comment by carsten989** [comment]
Don't think anybody is really monitoring GH issues here.
If this is still an issue for you, please create a JIRA issue at https://telecominfraproject.atlassian.net/jira/
Also feel free to post on Slack.
